@ Generated by gcc 2.95.3 20010315 (release)(ColdFire patches - 20010318 from http://fiddes.net/coldfire/)(uClinux XIP and shared lib patches from http://www.snapgear.com/) for ARM/elf
	.file	"encrypt_char.c"
.gcc2_compiled.:
	.global	c
	.section .rodata
	.align	2
	.type	 c,object
	.size	 c,4
c:
	.word	33
.text
	.align	2
	.global	encrypt_char
	.type	 encrypt_char,function
encrypt_char:
	@ args = 0, pretend = 0, frame = 4
	@ frame_needed = 1, current_function_anonymous_args = 0
	mov	ip, sp
	stmfd	sp!, {fp, ip, lr, pc}
	sub	fp, ip, #4
	sub	sp, sp, #4
	mov	r3, r0
	mov	r2, r3
	strb	r2, [fp, #-13]
	ldr	r3, .L11
	mov	r2, #7
	str	r2, [r3, #0]
	ldr	r3, .L11+4
	mov	r2, #0
	str	r2, [r3, #0]
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	cmp	r3, #96
	bls	.L5
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	cmp	r3, #109
	bls	.L4
	b	.L5
.L5:
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	cmp	r3, #64
	bls	.L3
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	cmp	r3, #77
	bls	.L4
	b	.L3
.L4:
	ldrb	r3, [fp, #-13]
	add	r2, r3, #13
	and	r3, r2, #255
	mov	r0, r3
	b	.L2
	b	.L6
.L3:
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	cmp	r3, #109
	bls	.L9
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	cmp	r3, #122
	bls	.L8
	b	.L9
.L9:
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	cmp	r3, #77
	bls	.L7
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	cmp	r3, #90
	bls	.L8
	b	.L7
.L8:
	ldrb	r3, [fp, #-13]
	sub	r2, r3, #13
	and	r3, r2, #255
	mov	r0, r3
	b	.L2
	b	.L6
.L7:
	ldrb	r3, [fp, #-13]	@ zero_extendqisi2
	mov	r0, r3
	b	.L2
.L12:
	.align	2
.L11:
	.word	a
	.word	b
.L10:
.L6:
.L2:
	ldmea	fp, {fp, sp, pc}
.Lfe1:
	.size	 encrypt_char,.Lfe1-encrypt_char
	.comm	a, 4	@ 4
	.comm	b, 4	@ 4
