# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1460123955);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1460124075);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1458546509);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1460123835);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1460123715);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1460124195);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1460123611267");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1460127211267");
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160209234718");
user_pref("browser.slowStartup.averageTime", 8964);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20160209234718");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1458632788983");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1458546451354");
user_pref("datareporting.policy.firstRunTime", "1458546388982");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 4405);
user_pref("datareporting.sessions.current.main", 141);
user_pref("datareporting.sessions.current.sessionRestored", 3737);
user_pref("datareporting.sessions.current.startTime", "1474820352479");
user_pref("datareporting.sessions.current.totalTime", 7);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.1", "{\"s\":1460123592368,\"a\":0,\"t\":7,\"c\":false,\"m\":141,\"fp\":5094,\"sr\":4990}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1464190306076,\"a\":1,\"t\":8,\"c\":true,\"m\":151,\"fp\":4149,\"sr\":3674}");
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1460123957);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455750937000,\"mt\":1455063905000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"45.0\",\"st\":1457098132000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"45.0\",\"st\":1457098133000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160209234718");
user_pref("gecko.mstone", "44.0.2");
user_pref("idle.lastDailyNotification", 1460124259);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1460123661);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160209234718");
user_pref("media.gmp-manager.lastCheck", 1460123659);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 26221);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1474820352);
user_pref("toolkit.telemetry.cachedClientID", "ea472f8e-f971-4306-91f8-ea70addf427e");
user_pref("toolkit.telemetry.previousBuildID", "20160209234718");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
